packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - bullmq@5.80.8

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - '@scarf/scarf'
